---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: todoapp
  labels: 
    app: todo

spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo

  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: vdocker0123/todo:user01

      
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: todo-configmap
              key: db-host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: todo-configmap
              key: db-port
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: todo-configmap
              key: db-name
        - name: SCHEME
          valueFrom:
            configMapKeyRef:
              name: todo-configmap
              key: scheme
        - name: USER_APP_HOST
          valueFrom:
            configMapKeyRef:
              name: todo-configmap
              key: user-app-host  
        - name: USER_APP_PORT
          valueFrom:
            configMapKeyRef:
              name: todo-configmap
              key: user-app-port          

        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: todo-secret
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: todo-secret
              key: db-password      

        resources:
          limits:
            cpu: 2048m
          requests:
            cpu: 100m
        ports:
        - containerPort: 8080 

        # livenessProbe:
        #   failureThreshold: 2
        #   httpGet:
        #     path: /task
        #     port: 8080
        #   initialDelaySeconds: 10
        #   periodSeconds: 30
        #   successThreshold: 1
        #   timeoutSeconds: 30   

      #   readinessProbe:
      #     failureThreshold: 2
      #     httpGet:
      #       path: /task
      #       port: 8080
      #     initialDelaySeconds: 10
      #     periodSeconds: 30
      #     successThreshold: 1
      #     timeoutSeconds: 30

      #   volumeMounts:
      #   - name: todovolume
      #     mountPath: "/data"
      #     readOnly: true   
      # volumes:  
      #   - name: todovolume
      #     secret: 
      #       secretName: todo-secret 
---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  selector:
    app: todo
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: todo-gateway
  namespace: test
spec:
  selector:
    istio: ingressgateway 
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"    
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: todo-virtualservice
spec:
  hosts:
  - "*"
  gateways:
  - test/todo-gateway
  http:
  - route:
    - destination:
        host: todo-service.default.svc.cluster.local
        port:
          number: 80    
